Deploy Viberoll-Backend AWS infrastructure

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,6 +32,20 @@ jobs:
         with:
           terraform_version: 1.6.6
 
+      - name: Restore AWS Secrets (if scheduled for deletion)
+        run: |
+            echo "🔄 Restoring secrets scheduled for deletion..."
+            aws secretsmanager list-secrets \
+            --region eu-west-2 \
+            --include-planned-deletion \
+            --query 'SecretList[].Name' \
+            --output text \
+            | tr '\t' '\n' \
+            | while read name; do
+                echo "🔁 Restoring $name"
+                aws secretsmanager restore-secret --region eu-west-2 --secret-id "$name" || echo "⚠️ Could not restore $name"
+            done
+          
       - name: Terraform Init
         run: terraform init
 
